ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

CREATE USER CSYT_Admin IDENTIFIED BY a;

CREATE TABLE CSYT_Admin.ThongBao (
    MaTB       INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    NoiDung    NVARCHAR2(1000), 
    NgayGio    TIMESTAMP, 
    DiaDiem    NVARCHAR2(1000), 
    CONSTRAINT PK_ThongBao_N04 PRIMARY KEY(MaTB)
);



