select name,status from dba_ols_status where name='OLS_CONFIGURE_STATUS';
--select * from DBA_SA_Policies;

EXECUTE SA_SYSDBA.DROP_POLICY('ACCESS_THONGBAO');

EXECUTE SA_SYSDBA.CREATE_POLICY('ACCESS_THONGBAO','OLS_THONGBAO');



GRANT EXECUTE ON SA_COMPONENTS TO CSYT_ADMIN;

GRANT EXECUTE ON SA_LABEL_ADMIN TO CSYT_ADMIN;

GRANT EXECUTE ON SA_POLICY_ADMIN TO CSYT_ADMIN;

GRANT EXECUTE ON SA_USER_ADMIN TO CSYT_ADMIN;

GRANT EXECUTE ON CHAR_TO_LABEL TO CSYT_ADMIN;


--level: Giám đốc
--compartment: ngoại trú
--group: trung/cận trung/ ngoại

EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_THONGBAO',30,'GDS','GIAM_DOC_SO');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_THONGBAO',20,'GDCS','GIAM_DOC_CSYT');
EXEC SA_COMPONENTS.CREATE_LEVEL('ACCESS_THONGBAO',10,'YBS','Y_BSI');


EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_THONGBAO',50,'CS','CHUYEN_SAU');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_THONGBAO',60,'NT','NOI_TRU');
EXEC SA_COMPONENTS.CREATE_COMPARTMENT('ACCESS_THONGBAO',70,'NGT','NGOAI_TRU');


EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_THONGBAO',100,'TT','TRUNG_TAM');
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_THONGBAO',200,'CTT','CAN_TRUNG_TAM');
EXEC SA_COMPONENTS.CREATE_GROUP('ACCESS_THONGBAO',300,'NTH','NGOAI_THANH');


--LV ONNLY
EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 100,label_value => 'GDS');


EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 110,label_value => 'GDCS:CS,NT:TT');
EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 120,label_value => 'GDCS:CS,NGT:CTT');
EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 130,label_value => 'GDCS:NGT:NTH');


EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 140,label_value => 'YBS:CS:TT');
EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 150,label_value => 'YBS:NT:CTT');
EXEC SA_LABEL_ADMIN.CREATE_LABEL(policy_name => 'ACCESS_THONGBAO',label_tag => 160,label_value => 'YBS:NGT:NTH');



EXEC SA_POLICY_ADMIN.APPLY_TABLE_POLICY(policy_name=>'ACCESS_THONGBAO',schema_name => 'CSYT_ADMIN',table_name => 'THONGBAO',table_options=>'READ_CONTROL,WRITE_CONTROL');

----
GRANT SELECT, INSERT, UPDATE ON ANNOUCEMENTS TO QLNV;

UPDATE QLNV.NHANVIEN

SET OLS_NHANVIEN = CHAR_TO_LABEL('ACCESS_THONGBAO','HS');


EXEC SA_USER_ADMIN.SET_USER_LABELS (policy_name=>'ACCESS_THONGBAO',user_name=>'CSYT_GDS',max_read_label=>'GDS',max_write_label=>'GDS',def_label=>'GDS');
EXEC SA_USER_ADMIN.SET_USER_LABELS (policy_name=>'ACCESS_THONGBAO',user_name=>'CSYT_GDCS',max_read_label=>'GDCS:CS,NT:TT',max_write_label=>'GDCS:CS,NT:TT',def_label=>'GDCS:CS,NT:TT');
EXEC SA_USER_ADMIN.SET_USER_LABELS (policy_name=>'ACCESS_THONGBAO',user_name=>'CSYT_YBS',max_read_label=>'YBS:CS:TT',max_write_label=>'YBS:CS:TT',def_label=>'YBS:CS:TT');



