grant select on dba_users to CSYT_Admin;
create or replace procedure CSYT_Admin.ShowAllUser (CUR out SYS_REFCURSOR)
as

    BEGIN
        Open CUR for SELECT USERNAME FROM dba_users where USERNAME like 'C##CSYT%';

    END;
    /
grant select on dba_roles to CSYT_Admin;
/
create or replace procedure CSYT_Admin.ShowAllRole (CUR out SYS_REFCURSOR)
as

    BEGIN
        Open CUR for SELECT ROLE FROM dba_roles where ROLE like 'C##CSYT_ROLE_%';

    END;
/
--CAU 6: 
CREATE ROLE CSYT_ROLE_BENHNHAN;
/
CREATE OR REPLACE VIEW CSYT_ADMIN.VIEW_BENHNHAN_SELFVIEW
AS
select MaBN,MaCSYT,TenBN,CSYT_ADMIN.DECRYPT(CMND,MABN||MACSYT) as CMND,  
CSYT_ADMIN.DECRYPT(SONHA,MABN||MACSYT) as SONHA,
CSYT_ADMIN.DECRYPT(TENDUONG,MABN||MACSYT) as TENDUONG,
CSYT_ADMIN.DECRYPT(QUANHUYEN,MABN||MACSYT) as QUANHUYEN,
CSYT_ADMIN.DECRYPT(TINHTP,MABN||MACSYT) as TINHTP,
NgaySinh,tiensubenh,tiensubenhgd,diungthuoc
FROM CSYT_Admin.BenhNhan
WHERE 'CSYT_'||MaBN = user
/

GRANT SELECT ON CSYT_ADMIN.VIEW_BENHNHAN_SELFVIEW TO CSYT_ROLE_BENHNHAN;
GRANT UPDATE ON CSYT_ADMIN.VIEW_BENHNHAN_SELFVIEW TO CSYT_ROLE_BENHNHAN;
GRANT EXECUTE ON CSYT_ADMIN.getUserRoles TO CSYT_ROLE_BENHNHAN;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_TENBN(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET TENBN=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_CMND(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET CMND=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_NGAYSINH(input IN DATE DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET NgaySinh=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_SONHA(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET SoNha=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_TENDUONG(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET TenDuong=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_QUANHUYEN(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET QuanHuyen=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_TINHTP(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET TinhTP=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_TIENSUBENH(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET TIENSUBENH=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_TIENSUBENHGD(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.VIEW_BENHNHAN_SELFVIEW
    SET TIENSUBENHGD=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
create or replace procedure CSYT_ADMIN.BENHNHAN_UPDATE_DIUNGTHUOC(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.BENHNHAN
    SET DIUNGTHUOC=input
    WHERE 'CSYT_'||MaBN = user;
END;
/
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_TENBN to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_CMND to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_NGAYSINH to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_SONHA to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_TENDUONG to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_QUANHUYEN to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_TINHTP to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_TIENSUBENH to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_TIENSUBENHGD to CSYT_ROLE_BENHNHAN;
grant execute on CSYT_ADMIN.BENHNHAN_UPDATE_DIUNGTHUOC to CSYT_ROLE_BENHNHAN;
/
CREATE OR REPLACE FUNCTION CSYT_ADMIN.BN_CONTROL(
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    if USER like '%BN%' then
        RETURN '''CSYT_''||MaBN=USER';
    ELSE
        RETURN '1=1';
    END IF;
END;
/
BEGIN DBMS_RLS.DROP_POLICY(
    object_schema   => 'CSYT_ADMIN',
    object_name     => 'BENHNHAN',
    policy_name     => 'BN_CONTROL'
);
END;

BEGIN DBMS_RLS.ADD_POLICY(
    object_schema   => 'CSYT_ADMIN',
    object_name     => 'BENHNHAN',
    policy_name     => 'BN_CONTROL',
    function_schema => 'CSYT_ADMIN',
    policy_function => 'BN_CONTROL',
    statement_types => 'SELECT,INSERT,DELETE,UPDATE',
    update_check    => TRUE
);
END;
/
CREATE OR REPLACE FUNCTION CSYT_ADMIN.NV_CONTROL(
    p_schema IN VARCHAR2,
    p_object IN VARCHAR2
)
RETURN VARCHAR2
AS
BEGIN
    if USER like '%NV%' then
        RETURN '''CSYT_''||MaNV=USER';
    ELSE
        RETURN '1=1';
    END IF;
END;
/

BEGIN DBMS_RLS.ADD_POLICY(
    object_schema   => 'CSYT_ADMIN',
    object_name     => 'NHANVIEN',
    policy_name     => 'NV_CONTROL',
    function_schema => 'CSYT_ADMIN',
    policy_function => 'NV_CONTROL',
    statement_types => 'SELECT,INSERT,DELETE,UPDATE',
    update_check    => TRUE
);
END;
/
CREATE ROLE CSYT_ROLE_NHANVIEN;
/
CREATE OR REPLACE VIEW CSYT_ADMIN.VIEW_NHANVIEN_SELFVIEW
AS
SELECT  MANV,HOTEN,PHAI,NGAYSINH,
CSYT_ADMIN.DECRYPT(CMND,MaNV||CSYT) as CMND,
CSYT_ADMIN.DECRYPT(QUEQUAN,MaNV||CSYT) AS QUEQUAN, SDT
FROM CSYT_Admin.NhanVien
WHERE 'CSYT_'||MaNV = user
/
GRANT SELECT ON CSYT_ADMIN.VIEW_NHANVIEN_SELFVIEW TO CSYT_ROLE_NHANVIEN;
GRANT UPDATE ON CSYT_ADMIN.VIEW_NHANVIEN_SELFVIEW TO CSYT_ROLE_NHANVIEN;
GRANT EXECUTE ON CSYT_ADMIN.getUserRoles TO CSYT_ROLE_NHANVIEN;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_HOTEN(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET HOTEN=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_PHAI(input IN NVARCHAR2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET PHAI=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_NGAYSINH(input IN date DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET NGAYSINH=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_CMND(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET CMND=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_QUEQUAN(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET QUEQUAN=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
create or replace procedure CSYT_ADMIN.NHANVIEN_UPDATE_SDT(input IN varchar2 DEFAULT NULL)
AS 
BEGIN
    UPDATE CSYT_ADMIN.NHANVIEN
    SET SDT=input
    WHERE 'CSYT_'||MaNV = user;
END;
/
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_HOTEN to CSYT_ROLE_NHANVIEN;
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_PHAI to CSYT_ROLE_NHANVIEN;
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_NGAYSINH to CSYT_ROLE_NHANVIEN;
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_CMND to CSYT_ROLE_NHANVIEN;
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_QUEQUAN to CSYT_ROLE_NHANVIEN;
grant execute on CSYT_ADMIN.NHANVIEN_UPDATE_SDT to CSYT_ROLE_NHANVIEN;

















/
--Cau 4:
create role CSYT_ROLE_BACSI;
/
CREATE OR REPLACE VIEW CSYT_ADMIN.VIEW_BACSI_HSBA
as SELECT * FROM CSYT_ADMIN.HSBA
WHERE CSYT_ADMIN.HSBA.MAHSBA IN (SELECT MAHSBA FROM CSYT_ADMIN.HSBA 
                                WHERE 'CSYT_'||MaBS = user);
/
CREATE OR REPLACE VIEW CSYT_ADMIN.VIEW_BACSI_HSBA_DV
as SELECT * FROM CSYT_ADMIN.HSBA_DV
WHERE CSYT_ADMIN.HSBA_DV.MAHSBA IN (SELECT MAHSBA FROM CSYT_ADMIN.HSBA 
                                WHERE 'CSYT_'||MaBS = user);
/
CREATE OR REPLACE VIEW CSYT_ADMIN.VIEW_BACSI_BENHNHAN
as select MaBN,MaCSYT,TenBN,CSYT_ADMIN.DECRYPT(CMND,MABN||MACSYT) as CMND,  
CSYT_ADMIN.DECRYPT(SONHA,MABN||MACSYT) as SONHA,
CSYT_ADMIN.DECRYPT(TENDUONG,MABN||MACSYT) as TENDUONG,
CSYT_ADMIN.DECRYPT(QUANHUYEN,MABN||MACSYT) as QUANHUYEN,
CSYT_ADMIN.DECRYPT(TINHTP,MABN||MACSYT) as TINHTP,
tiensubenh,tiensubenhgd,diungthuoc
FROM CSYT_Admin.BenhNhan
/
CREATE OR REPLACE PROCEDURE CSYT_ADMIN.BACSI_SELECT_BENHNHAN(
MABN IN CHAR DEFAULT NULL,
CMND IN CHAR DEFAULT NULL,
BENHNHAN OUT SYS_REFCURSOR)
AS 
BEGIN
    OPEN CSYT_ADMIN.BACSI_SELECT_BENHNHAN.BENHNHAN FOR 
    SELECT * FROM CSYT_ADMIN.VIEW_BACSI_BENHNHAN
    WHERE MABN = CSYT_ADMIN.BACSI_SELECT_BENHNHAN.MABN 
    OR CMND = CSYT_ADMIN.BACSI_SELECT_BENHNHAN.CMND;
END;
/
GRANT SELECT ON CSYT_ADMIN.VIEW_BACSI_HSBA TO CSYT_ROLE_BACSI;
GRANT SELECT ON CSYT_ADMIN.VIEW_BACSI_HSBA_DV TO CSYT_ROLE_BACSI;
GRANT SELECT ON CSYT_ADMIN.VIEW_BACSI_BENHNHAN TO CSYT_ROLE_BACSI;
GRANT EXECUTE ON CSYT_ADMIN.BACSI_SELECT_BENHNHAN TO CSYT_ROLE_BACSI;
GRANT EXECUTE ON CSYT_ADMIN.getUserRoles TO CSYT_ROLE_BACSI;
/
------------------------------------